# PURPOSE: Define tasks for building, running, and managing the auto_shutdown application
# SCOPE: Build and Development Automation
# STATUS: Stable
version: '3'

includes:
  systemd:
    taskfile: taskfile.systemd.yaml

tasks:
  build-gcp:
    desc: Build the auto_shutdown binary for Linux AMD64
    dir: auto_shutdown/cmd/gcp
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o ../../../build/auto_shutdown_gcp -ldflags="-s -w" main.go

  build-azure:
    desc: Build the auto_shutdown_azure binary for Linux AMD64
    dir: auto_shutdown/cmd/azure
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o ../../../build/auto_shutdown_azure -ldflags="-s -w" main.go

  build-universal:
    desc: Build the auto_shutdown binary for Linux AMD64
    dir: auto_shutdown/cmd/universal
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o ../../../build/auto_shutdown_universal -ldflags="-s -w" main.go

  build:
    desc: Build the auto_shutdown binary
    deps:
      - build-gcp
      - build-azure
      - build-universal

  dev-gcp:
    desc: Run the auto_shutdown source using 'go run'
    dir: auto_shutdown/cmd/gcp
    cmds:
      - go run main.go

  dev-azure:
    desc: Run the auto_shutdown_azure source using 'go run'
    dir: auto_shutdown/cmd/azure
    cmds:
      - go run main.go

  dev-universal:
    desc: Run the auto_shutdown_universal source using 'go run'
    dir: auto_shutdown/cmd/universal
    env: # for testing purposes
      SHUTDOWN_THRESHOLD: 0.20
      SHUTDOWN_INTERVALS: 60
      SHUTDOWN_SLEEP_TIME: 30
      INITIAL_DELAY: 15
    cmds:
      - go run main.go

  run-gcp:
    desc: Run the auto_shutdown binary
    dir: build
    cmds:
      - ./auto_shutdown_gcp

  run-azure:
    desc: Run the auto_shutdown_azure binary
    dir: build
    cmds:
      - ./auto_shutdown_azure

  run-universal:
    desc: Run the auto_shutdown_universal binary
    dir: build
    cmds:
      - ./auto_shutdown_universal

  clean:
    desc: Remove the built binary
    dir: build
    cmds:
      - rm -f auto_shutdown_gcp
      - rm -f auto_shutdown_azure
      - rm -f auto_shutdown_universal

  fmt:
    desc: Format the code
    dir: auto_shutdown
    cmds:
      - go fmt ./...

  default:
    desc: Default task to list tasks
    cmds:
      - task --list